# Generated by Django 5.2.9 on 2025-12-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('record_type', models.CharField(choices=[('consultation', 'Consultation'), ('prescription', 'Ordonnance'), ('test', 'Test Médical'), ('vaccination', 'Vaccination'), ('surgery', 'Chirurgie'), ('hospitalization', 'Hospitalisation'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_files/%Y/%m/%d/')),
                ('is_emergency', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_date', models.DateField()),
                ('result', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('normal_range', models.CharField(blank=True, max_length=100)),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='test_results/%Y/%m/%d/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='medical_records.medicalrecord')),
            ],
        ),
    ]
